### ISSUE TITLE
Cannot connect to channel?

### ISSUE THREAD

**Issue by glitchto** [TwitchLib/TwitchLib.Unity#35] opened 2018-06-24 10:07 UTC
"BadStateExeption: Must be connected to at least one channel." at event, even with provided client class, correct initialization, non capitalized channel names, double checked keys.

**Comment by swiftyspiffy** [comment] 2018-06-24 10:12
Can you share your code?

**Comment by glitchto** [comment] 2018-06-24 10:22
I first followed the tutorial by HonestDanGames you linked, after I used your class "Chat Client for Unity"
which by the way has these variables missing "Args" from their name's end:
TwitchLib.Client.Events.OnJoinedChannel
TwitchLib.Client.Events.OnChatCommandReceived
... have passed correct params:
`public class TwitchCL : MonoBehaviour
{
    private Client _client;
    private string channelName = "mychannel"; //privacy
    private string botName = "mychannelbot";
    void Start()
    {
        //Set to run in minimized mode
        Application.runInBackground = true;
        //Create Credentials instance
        ConnectionCredentials credentials = new ConnectionCredentials(botName, Secrets.botAccessToken);
        //Create new instance of Chat Client
        _client = new Client();
        _client.Initialize(credentials, channelName);
        _client.OnMessageReceived += _client_OnMessageReceived; ;
        _client.Connect();

    }`

**Comment by glitchto** [comment] 2018-06-24 10:30
Oh no, its because my class name is TwitchCL and not TwitchClient. I'm sorry, I didn't realize it matters. Thread can be deleted .. thank you for fast reply though!

**Comment by swiftyspiffy** [comment] 2018-06-24 11:22
That code looks like it’d work in the normal (not unity) library. You might also try listening to OnConnected, OnJoinedChannel, and OnSendReceiveData events. The latter will fire every time a piece of data is received from Twitch, and is great for debugging problems.

Other than that, you’ll probably have to wait for Lucky to respond

**Comment by RRickkert** [comment] 2018-06-24 11:33
Could you provide your Unity version? As of Unity 2018 the TwitchClient is no longer functional. See: https://fogbugz.unity3d.com/default.asp?1045497_7ifkb9kvjpn7113n This might also be the case for some later versions of Unity 2017. This bug report is specifically for WebSocket4Net, however, TwitchLib's client uses that in the background, so it won't work.

I created a Unity package which you an import into any empty unity project, press play, and it should show "opened" in the log. If it doesn't that means your Unity version won't work with TwitchLib's Client: [https://cdn.discordapp.com/attachments/415976614954795018/458754439793213453/WebSocket4Net_Unity_TestPackage.unitypackage](url)

**Comment by glitchto** [comment] 2018-06-24 11:36
Hello, I do have the latest Unity installed, yes. Your package link is dead for me. 
Should I revert Unity and for what version? Or is there another way? 
Thank you.

**Comment by RRickkert** [comment] 2018-06-24 11:36
I just noticed it didn't work, trying to fix it D:

**Comment by RRickkert** [comment] 2018-06-24 11:38
Can you try to just copy paste the link instead? It works here. Github doesn't like links for whatever reason?
If you indeed have the latest version, you'll have to revert to an older version sadly..

**Comment by glitchto** [comment] 2018-06-24 11:39
What exact version would you recommend?

**Comment by glitchto** [comment] 2018-06-24 11:40
Would you recommend other API that works without uninstalling Unity?

**Comment by RRickkert** [comment] 2018-06-24 12:07
From the **official** releases, I can confirm **working**:
* Unity 2017.4.6f1 (LTS)
* Unity 2017.3.1f1

From the **beta** releases, I can confirm **working**:
* Unity 2018.2.0b1

From the **official** releases, I can confirm **broken**:
* Unity 2018.1.6f1
* Unity 2018.1.5f1

From the **official** releases, I can confirm **broken**:
* Unity 2018.2.0b4 - Unity 2018.2.0b9

So personally I would recommend the latest version of Unity 2017 for now, which has LTS (long term support).

I can also recommend installing the Unity Hub, to easily manage your Unity versions, so it makes it easier to have multiple versions installed, and switching between them is much easier.

As for any other API. the TwitchLib.API module should work just fine. It's just the TwitchLib.Client which is broken.
For any other Twitch chat bot client, I don't know any.

**Comment by glitchto** [comment] 2018-06-24 12:09
Thanks, I do have Unity Hub, see if 2017.4.6f1 (LTS) does it.

**Comment by glitchto** [comment] 2018-06-24 12:33
Installed, works like charm. Thank you !

**Comment by RRickkert** [comment] 2018-06-24 13:17
See issue #36 for more information

**Comment by swiftyspiffy** [comment] 2018-06-26 21:04
Will go ahead and close this. Feel free to reopen as necessary.

**Closed by swiftyspiffy** 2018-06-26 21:04 UTC
